apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teams
  name: teams
  labels:
    app: teams
spec:
  selector:
    matchLabels:
      app: teams
  template:
    metadata:
      labels:
        app: teams
        name: teams
    spec:
      containers:
        - name: teams
          image: sindhutrisha/sindhu/teams
          imagePullPolicy: Always
        
          env:
            - name: SERVICE_NAME
              value: "go-app"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "localhost:4317"
            - name: INSECURE_MODE
              value: "true"
        
          ports:
        
        
          - containerPort: 3333
            name: http
        
        
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
        