apiVersion: v1
kind: Service
metadata:
  namespace: teams
  labels:
    app: teams
  name: teams
spec:
  ports:
  
    - protocol: TCP
      port: 3333
      targetPort: 3333
   
   
  selector:
    app: teams
  type: ClusterIP
